<<<<<<< HEAD
# Generated by Django 3.1.5 on 2021-02-22 18:38
=======
# Generated by Django 3.1.6 on 2021-02-23 23:05
>>>>>>> 64440652de38effe94ad0e1b65ace0989d99916c

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afastamento',
            fields=[
                ('id_afastamento', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Código')),
                ('tipificacao', models.CharField(max_length=50, verbose_name='Tipo de afastamento')),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Afastamento',
                'verbose_name_plural': 'Afastamentos',
            },
        ),
        migrations.CreateModel(
            name='EnderecoServ',
            fields=[
                ('id_endereco_serv', models.AutoField(primary_key=True, serialize=False)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
                ('municipio', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=100)),
            ],
            options={
<<<<<<< HEAD
                'verbose_name': 'EnderecoServ',
                'verbose_name_plural': 'EnderecoServidores',
=======
                'verbose_name': 'Endereço do Servidor',
                'verbose_name_plural': 'Endereços de Servidores',
>>>>>>> 64440652de38effe94ad0e1b65ace0989d99916c
            },
        ),
        migrations.CreateModel(
            name='EnderecoSetor',
            fields=[
                ('id_endereco_setor', models.AutoField(primary_key=True, serialize=False)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
                ('municipio', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=100)),
            ],
            options={
<<<<<<< HEAD
                'verbose_name': 'EnderecoSetor',
                'verbose_name_plural': 'EnderecoSetores',
=======
                'verbose_name': 'Endereço do Setor',
                'verbose_name_plural': 'Enderecos dos Setores',
>>>>>>> 64440652de38effe94ad0e1b65ace0989d99916c
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id_equipe', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('hora_inicial', models.TimeField()),
                ('categoria', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
            },
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id_funcao', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
<<<<<<< HEAD
                'verbose_name': 'Funcao',
                'verbose_name_plural': 'Funcoes',
=======
                'verbose_name': 'Função',
                'verbose_name_plural': 'Funções',
>>>>>>> 64440652de38effe94ad0e1b65ace0989d99916c
            },
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id_regiao', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
<<<<<<< HEAD
                'verbose_name': 'Regiao',
                'verbose_name_plural': 'Regioes',
=======
                'verbose_name': 'Região',
                'verbose_name_plural': 'Regiões',
>>>>>>> 64440652de38effe94ad0e1b65ace0989d99916c
            },
        ),
        migrations.CreateModel(
            name='StatusFuncional',
            fields=[
                ('id_status_funcional', models.AutoField(primary_key=True, serialize=False)),
                ('nome_status', models.CharField(max_length=50)),
                ('descricao_status', models.CharField(max_length=100)),
            ],
            options={
<<<<<<< HEAD
                'verbose_name': 'StatusFuncional',
                'verbose_name_plural': 'StatusFuncionais',
=======
                'verbose_name': 'Status Funcional',
                'verbose_name_plural': 'Status Funcionais',
>>>>>>> 64440652de38effe94ad0e1b65ace0989d99916c
            },
        ),
        migrations.CreateModel(
            name='TipoJornada',
            fields=[
                ('id_tipo_jornada', models.AutoField(primary_key=True, serialize=False)),
                ('carga_horaria', models.PositiveIntegerField()),
                ('tipificacao', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
<<<<<<< HEAD
                'verbose_name': 'TipoJornada',
                'verbose_name_plural': 'TipoJornadas',
=======
                'verbose_name': 'Tipo de Jornada',
                'verbose_name_plural': 'Tipos de Jornadas',
>>>>>>> 64440652de38effe94ad0e1b65ace0989d99916c
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id_setor', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nome', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('setor_sede', models.BooleanField(default=False)),
                ('fk_endereco_setor', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='namp.enderecosetor', verbose_name='Endereço')),
                ('fk_regiao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='namp.regiao', verbose_name='Região')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id_matricula', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Matrícula')),
                ('vinculo', models.CharField(max_length=3)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('sexo', models.CharField(max_length=1)),
                ('dt_nasc', models.DateField()),
                ('cargo', models.CharField(max_length=50)),
                ('tipo_vinculo', models.CharField(max_length=50)),
                ('regime_juridico', models.CharField(max_length=50)),
                ('situacao', models.BooleanField(default=False)),
                ('fk_endereco_serv', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='namp.enderecoserv', verbose_name='Endereço')),
                ('fk_equipe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='namp.equipe', verbose_name='Equipe')),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id_jornada', models.AutoField(primary_key=True, serialize=False)),
                ('data_jornada', models.DateField()),
                ('assiduidade', models.BooleanField(default=False)),
                ('fk_equipe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='namp.equipe', verbose_name='Equipe')),
                ('fk_servidor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='namp.servidor', verbose_name='Servidor')),
                ('fk_tipo_jornada', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='namp.tipojornada', verbose_name='Tipo Jornada')),
            ],
            options={
                'verbose_name': 'Jornada',
                'verbose_name_plural': 'Jornadas',
            },
        ),
        migrations.CreateModel(
            name='HistStatusFuncional',
            fields=[
                ('id_hist_funcional', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('fk_servidor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='namp.servidor', verbose_name='Servidor')),
                ('fk_status_funcional', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='namp.statusfuncional', verbose_name='Status Funcional')),
            ],
            options={
<<<<<<< HEAD
                'verbose_name': 'HistStatusFuncional',
                'verbose_name_plural': 'HistStatusFuncionais',
=======
                'verbose_name': 'Histórico de Status Funcional',
                'verbose_name_plural': 'Histórico de Status Funcionais',
>>>>>>> 64440652de38effe94ad0e1b65ace0989d99916c
            },
        ),
        migrations.CreateModel(
            name='HistLotacao',
            fields=[
                ('id_hist_lotacao', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('fk_equipe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='namp.equipe', verbose_name='Equipe')),
                ('fk_servidor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='namp.servidor', verbose_name='Servidor')),
            ],
            options={
<<<<<<< HEAD
                'verbose_name': 'HistLotacao',
                'verbose_name_plural': 'HistLotacoes',
=======
                'verbose_name': 'Histórico de Lotação',
                'verbose_name_plural': 'Históricos de Lotações',
>>>>>>> 64440652de38effe94ad0e1b65ace0989d99916c
            },
        ),
        migrations.CreateModel(
            name='HistFuncao',
            fields=[
                ('id_hist_funcao', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('fk_funcao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='namp.funcao', verbose_name='Função')),
                ('fk_servidor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='namp.servidor', verbose_name='Servidor')),
            ],
            options={
<<<<<<< HEAD
                'verbose_name': 'HistFuncao',
                'verbose_name_plural': 'HistFuncoes',
=======
                'verbose_name': 'Histórico de Função',
                'verbose_name_plural': 'Históricos de Funcões',
>>>>>>> 64440652de38effe94ad0e1b65ace0989d99916c
            },
        ),
        migrations.CreateModel(
            name='HistAfastamento',
            fields=[
                ('id_hist_afastamento', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicial', models.DateField()),
                ('duracao', models.PositiveIntegerField()),
                ('fk_afastamento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='namp.afastamento', verbose_name='Afastamento')),
                ('fk_servidor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='namp.servidor', verbose_name='Servidor')),
            ],
            options={
<<<<<<< HEAD
                'verbose_name': 'HistAfastamento',
                'verbose_name_plural': 'HistAfastamentos',
=======
                'verbose_name': 'Histório de Afastamento',
                'verbose_name_plural': 'Históricos de Afastamentos',
>>>>>>> 64440652de38effe94ad0e1b65ace0989d99916c
            },
        ),
        migrations.AddField(
            model_name='equipe',
            name='fk_setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='namp.setor', verbose_name='Setor'),
        ),
        migrations.CreateModel(
            name='ContatoServ',
            fields=[
                ('id_contato_serv', models.AutoField(primary_key=True, serialize=False)),
<<<<<<< HEAD
                ('tipo_contato', models.CharField(choices=[('Telefone Celular', 'Telefone Celular'), ('Telefone Fixo', 'Telefone Fixo'), ('E-mail', 'E-mail')], max_length=100)),
                ('contato', models.CharField(max_length=100)),
                ('fk_servidor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='namp.servidor')),
            ],
            options={
                'verbose_name': 'ContatoServidor',
                'verbose_name_plural': 'ContatoServidores',
=======
                ('tipo_contato', models.CharField(choices=[('Telefone Celular', 'Telefone Celular'), ('Telefone Fixo', 'Telefone Fixo'), ('E-mail', 'E-mail')], max_length=100, verbose_name='Tipo de contato')),
                ('contato', models.CharField(max_length=100)),
                ('fk_servidor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='namp.servidor', verbose_name='Servidor')),
            ],
            options={
                'verbose_name': 'Contato do Servidor',
                'verbose_name_plural': 'Contatos de Servidores',
>>>>>>> 64440652de38effe94ad0e1b65ace0989d99916c
            },
        ),
        migrations.CreateModel(
            name='ContatoEquipe',
            fields=[
                ('id_contato_equipe', models.AutoField(primary_key=True, serialize=False)),
                ('tipificacao', models.CharField(choices=[('Telefone Celular', 'Telefone Celular'), ('Telefone Fixo', 'Telefone Fixo'), ('E-mail', 'E-mail')], max_length=50, verbose_name='Tipo de contato')),
                ('contato', models.CharField(max_length=50)),
                ('fk_equipe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='namp.equipe', verbose_name='Equipe')),
            ],
            options={
<<<<<<< HEAD
                'verbose_name': 'ContatoEquipe',
                'verbose_name_plural': 'ContatoEquipes',
=======
                'verbose_name': 'Contato da Equipe',
                'verbose_name_plural': 'Contato das Equipes',
>>>>>>> 64440652de38effe94ad0e1b65ace0989d99916c
            },
        ),
    ]
