# Generated by Django 3.1.5 on 2021-03-01 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contatoserv',
            options={'verbose_name': 'Contato do Servidor', 'verbose_name_plural': 'Contatos do Servidor'},
        ),
        migrations.AlterModelOptions(
            name='regiao',
            options={'ordering': ['id_regiao'], 'verbose_name': 'Região', 'verbose_name_plural': 'Regiões'},
        ),
        migrations.AlterField(
            model_name='afastamento',
            name='descricao',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enderecosetor',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='enderecosetor',
            name='cep',
            field=models.CharField(blank=True, default='77000000', max_length=8),
        ),
        migrations.AlterField(
            model_name='enderecosetor',
            name='endereco',
            field=models.CharField(default='Não registrado', max_length=100),
        ),
        migrations.AlterField(
            model_name='enderecosetor',
            name='municipio',
            field=models.CharField(default='Palmas', max_length=100),
        ),
        migrations.AlterField(
            model_name='enderecosetor',
            name='numero',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='enderecosetor',
            name='uf',
            field=models.CharField(default='TO', max_length=2),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='cpf',
            field=models.CharField(max_length=12, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='dt_nasc',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='regime_juridico',
            field=models.CharField(max_length=50, verbose_name='Regime Jurídico'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='tipo_vinculo',
            field=models.CharField(max_length=50, verbose_name='Tipo de Vínculo'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='vinculo',
            field=models.CharField(max_length=3, verbose_name='Vínculo'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='fk_regiao',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.RESTRICT, to='namp.regiao', verbose_name='Região'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Setor Ativo'),
        ),
    ]
