# Generated by Django 3.1.7 on 2021-06-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da exclusão'),
        ),
    ]
