# Generated by Django 3.1.7 on 2021-04-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='cf',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II')], max_length=2, verbose_name='Curso de Formação'),
        ),
    ]
