# Generated by Django 3.1.7 on 2021-04-30 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jornada',
            unique_together={('fk_servidor', 'data_jornada')},
        ),
    ]
