# Generated by Django 3.1.7 on 2021-07-05 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id_escala', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('fk_jornada', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='namp.jornada', verbose_name='Jornada')),
            ],
        ),
    ]
