# Generated by Django 3.2 on 2021-04-16 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusfuncional',
            old_name='tipificacao',
            new_name='nome',
        ),
    ]
