# Generated by Django 3.1.5 on 2021-05-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcao',
            name='id_funcao',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
