# Generated by Django 3.1.5 on 2021-03-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecosetor',
            name='municipio',
            field=models.CharField(default='Não registrado', max_length=100),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='regime_juridico',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=25, verbose_name='Regime Jurídico'),
        ),
    ]
