# Generated by Django 3.2 on 2021-07-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodoacao',
            options={'ordering': ['data_inicial'], 'verbose_name': 'Período', 'verbose_name_plural': 'Períodos'},
        ),
        migrations.AlterField(
            model_name='periodoacao',
            name='data_inicial',
            field=models.DateTimeField(),
        ),
    ]
