# Generated by Django 3.1.5 on 2021-05-05 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jornada',
            unique_together={('fk_servidor', 'data_jornada')},
        ),
    ]
