# Generated by Django 3.1.7 on 2021-06-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatoserv',
            name='tipo_contato',
            field=models.CharField(choices=[('Telefone Celular', 'Telefone Celular'), ('Telefone Fixo', 'Telefone Fixo')], max_length=100, verbose_name='Tipo de contato'),
        ),
    ]
