# Generated by Django 3.2 on 2021-05-07 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afastamento',
            options={'ordering': ['id_afastamento'], 'verbose_name': 'Afastamento', 'verbose_name_plural': 'Afastamentos'},
        ),
        migrations.AddField(
            model_name='jornada',
            name='fk_afastamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='namp.afastamento', verbose_name='Afastamento'),
        ),
    ]
