# Generated by Django 3.2 on 2021-04-17 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afastamento',
            options={'ordering': ['nome'], 'verbose_name': 'Afastamento', 'verbose_name_plural': 'Afastamentos'},
        ),
    ]
