# Generated by Django 3.1.5 on 2021-03-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecosetor',
            name='municipio',
            field=models.CharField(default='Não registrado', max_length=100),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='cargo',
            field=models.CharField(choices=[('AEP', 'Agente de Execução Penal'), ('AAE', 'Agente Analista em Execução Penal'), ('AA', 'Assistente Administrativo'), ('AXA', 'Auxiliar Administrativo'), ('ASG', 'Auxiliar de Serviços Gerais'), ('ASS', 'Agente de Segurança Socioeducativo'), ('AES', 'Agente Especialista Socioeducativo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='regime_juridico',
            field=models.CharField(choices=[('C', 'CLT'), ('E', 'Estatutário')], max_length=25, verbose_name='Regime Jurídico'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='tipo_vinculo',
            field=models.CharField(choices=[('Contrato', 'Contrato'), ('Concursado', 'Concursado'), ('Estágio', 'Estágio'), ('Jovem Aprendiz', 'Jovem Aprendiz'), ('Terceirizado', 'Terceirizado')], max_length=25, verbose_name='Tipo de Vínculo'),
        ),
    ]
