# Generated by Django 3.1.7 on 2021-04-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0002_auto_20210425_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='cf',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('N', 'Nenhum')], max_length=3, verbose_name='Curso de Formação'),
        ),
    ]
