# Generated by Django 3.2 on 2021-04-16 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0002_rename_tipificacao_statusfuncional_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afastamento',
            options={'ordering': ['tipificacao'], 'verbose_name': 'Afastamento', 'verbose_name_plural': 'Afastamentos'},
        ),
        migrations.AlterModelOptions(
            name='enderecoserv',
            options={'ordering': ['uf', 'municipio', 'endereco'], 'verbose_name': 'Endereço do Servidor', 'verbose_name_plural': 'Endereço do Servidor'},
        ),
        migrations.AlterModelOptions(
            name='enderecosetor',
            options={'ordering': ['uf', 'municipio', 'endereco'], 'verbose_name': 'Endereço do Setor', 'verbose_name_plural': 'Enderecos dos Setores'},
        ),
        migrations.AlterModelOptions(
            name='equipe',
            options={'ordering': ['nome'], 'verbose_name': 'Equipe', 'verbose_name_plural': 'Equipes'},
        ),
        migrations.AlterModelOptions(
            name='funcao',
            options={'ordering': ['nome'], 'verbose_name': 'Função', 'verbose_name_plural': 'Funções'},
        ),
        migrations.AlterModelOptions(
            name='jornada',
            options={'ordering': ['data_jornada'], 'verbose_name': 'Jornada', 'verbose_name_plural': 'Jornadas'},
        ),
        migrations.AlterModelOptions(
            name='regiao',
            options={'ordering': ['nome'], 'verbose_name': 'Região', 'verbose_name_plural': 'Regiões'},
        ),
        migrations.AlterModelOptions(
            name='servidor',
            options={'ordering': ['nome'], 'verbose_name': 'Servidor', 'verbose_name_plural': 'Servidores'},
        ),
        migrations.AlterModelOptions(
            name='setor',
            options={'ordering': ['nome'], 'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
        migrations.AlterModelOptions(
            name='statusfuncional',
            options={'ordering': ['nome'], 'verbose_name': 'Status Funcional', 'verbose_name_plural': 'Status Funcionais'},
        ),
        migrations.AlterModelOptions(
            name='tipojornada',
            options={'ordering': ['tipificacao'], 'verbose_name': 'Tipo de Jornada', 'verbose_name_plural': 'Tipos de Jornadas'},
        ),
        migrations.AddField(
            model_name='histlotacao',
            name='fk_setor',
            field=models.ForeignKey(default='040.UPPMW', on_delete=django.db.models.deletion.RESTRICT, to='namp.setor', verbose_name='Sertor'),
            preserve_default=False,
        ),
    ]
