# Generated by Django 3.1.7 on 2021-06-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0002_auto_20210624_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatoserv',
            name='contato',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contatoserv',
            name='tipo_contato',
            field=models.CharField(choices=[('Telefone Celular', 'Telefone Celular'), ('Telefone Fixo', 'Telefone Fixo')], max_length=50, verbose_name='Tipo de contato'),
        ),
    ]
