# Generated by Django 3.1.5 on 2021-03-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0002_auto_20210315_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='regime_juridico',
            field=models.CharField(choices=[('CLT', 'CLT'), ('Estatutário', 'Estatutário')], max_length=25, verbose_name='Regime Jurídico'),
        ),
    ]
