# Generated by Django 3.1.5 on 2021-05-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0002_auto_20210506_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcao',
            name='nome',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
