# Generated by Django 3.1.5 on 2021-05-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0002_auto_20210505_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='cargo',
            field=models.CharField(choices=[('Agente de Execução Penal', 'Agente de Execução Penal'), ('Agente Analista em Execução Penal', 'Agente Analista em Execução Penal'), ('Assistente Administrativo', 'Assistente Administrativo'), ('Auxiliar Administrativo', 'Auxiliar Administrativo'), ('Auxiliar de Serviços Gerais', 'Auxiliar de Serviços Gerais'), ('Agente de Segurança Socioeducativo', 'Agente de Segurança Socioeducativo'), ('Agente Especialista Socioeducativo', 'Agente Especialista Socioeducativo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='cf',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('Nenhum', 'Nenhum')], max_length=10, verbose_name='Curso de Formação'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='regime_juridico',
            field=models.CharField(choices=[('CLT', 'CLT'), ('Estatutário', 'Estatutário')], max_length=25, verbose_name='Regime Jurídico'),
        ),
    ]
