# Generated by Django 3.2 on 2021-05-07 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0002_auto_20210507_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jornada',
            name='fk_afastamento',
        ),
        migrations.AddField(
            model_name='jornada',
            name='fk_histafastamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='namp.histafastamento', verbose_name='Motivo da Ausência'),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='assiduidade',
            field=models.BooleanField(default=True),
        ),
    ]
