# Generated by Django 3.2 on 2021-06-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0002_alter_servidor_fk_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
