# Generated by Django 3.2 on 2021-06-17 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('namp', '0003_equipe_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='servidor',
            name='fk_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
