# Generated by Django 3.2 on 2021-05-07 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0003_auto_20210507_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jornada',
            name='fk_histafastamento',
        ),
        migrations.AddField(
            model_name='jornada',
            name='fk_afastamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='namp.afastamento', verbose_name='Motivo da Ausência'),
        ),
    ]
