# Generated by Django 3.1.5 on 2021-05-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0003_auto_20210505_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jornada',
            options={'ordering': ['-fk_equipe__nome', '-fk_servidor__nome', 'data_jornada'], 'verbose_name': 'Jornada', 'verbose_name_plural': 'Jornadas'},
        ),
        migrations.RenameField(
            model_name='afastamento',
            old_name='nome',
            new_name='tipificacao',
        ),
    ]
