# Generated by Django 3.1.5 on 2021-05-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0003_auto_20210506_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcao',
            name='simbolo',
            field=models.CharField(max_length=25, verbose_name='Símbolo'),
        ),
        migrations.AlterUniqueTogether(
            name='funcao',
            unique_together={('nome',)},
        ),
    ]
