# Generated by Django 3.1.5 on 2021-05-06 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0004_auto_20210506_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcao',
            options={'ordering': ['simbolo'], 'verbose_name': 'Função', 'verbose_name_plural': 'Funções'},
        ),
    ]
