# Generated by Django 3.1.7 on 2021-03-15 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0004_auto_20210315_1508'),
        ('namp', '0002_auto_20210315_1409'),
    ]

    operations = [
    ]
