# Generated by Django 3.2 on 2021-06-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0004_auto_20210616_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
