# Generated by Django 3.2 on 2021-05-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0004_auto_20210507_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornada',
            name='assiduidade',
            field=models.BooleanField(default=False),
        ),
    ]
