# Generated by Django 3.2 on 2021-06-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0005_equipe_deleted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
