# Generated by Django 3.1.5 on 2021-05-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0005_auto_20210506_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histfuncao',
            name='data_final',
            field=models.DateField(blank=True, null=True),
        ),
    ]
