# Generated by Django 3.1.5 on 2021-03-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0005_merge_20210315_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='tipo_vinculo',
            field=models.CharField(choices=[('Contrato', 'Contrato'), ('Concursado', 'Concursado'), ('Estágio', 'Estágio'), ('Jovem Aprendiz', 'Jovem Aprendiz'), ('Terceirizado', 'Terceirizado')], max_length=25, verbose_name='Tipo de Vínculo'),
        ),
    ]
