# Generated by Django 3.1.7 on 2021-03-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0006_auto_20210316_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='cargo',
            field=models.CharField(choices=[('AEP', 'Agente de Execução Penal'), ('AAE', 'Agente Analista em Execução Penal'), ('AA', 'Assistente Administrativo'), ('AXA', 'Auxiliar Administrativo'), ('ASG', 'Auxiliar de Serviços Gerais'), ('ASS', 'Agente de Segurança Socioeducativo'), ('AES', 'Agente Especialista Socioeducativo')], max_length=50),
        ),
    ]
