# Generated by Django 3.1.7 on 2021-03-24 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0007_auto_20210323_2054'),
        ('namp', '0002_auto_20210317_1829'),
    ]

    operations = [
    ]
