# Generated by Django 3.1.7 on 2021-03-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0008_merge_20210323_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afastamento',
            name='descricao',
            field=models.TextField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='afastamento',
            name='tipificacao',
            field=models.CharField(choices=[('36', 'Afastamento Falencimento em Famímilia'), ('94', 'Afastamento Nascimento ou Adoção Filho'), ('76', 'Afastamento para Curso de Formação - Não Remunerado'), ('73', 'Afastamento para Finalização de Trabalho de Curso'), ('3', 'Aguadando Exercício - Término Cessão'), ('1', 'Aguardando Declaração de Exercicio, Afastamento até 15 dias'), ('114', 'Atestado Médico'), ('145', 'Atestado Medico Suspeita COVID-19'), ('31', 'Doação de Sangue'), ('6', 'Exercício de Mandato Eletivo'), ('43', 'Falta Integral'), ('103', 'Falta Integral - Nao Retornou ao Exercício'), ('116', 'Folga do TRE'), ('51', 'Licença Maternidade'), ('46', 'Licença Motivo de Doença em Pessoa da Familia'), ('45', 'Licença para Tratamento de Saúde'), ('77', 'Licença para Tratamento de Saúde (Prorrogação)'), ('8', 'Licença para Tratar de Interesses Particulares'), ('115', 'Ponto Facultativo do Aniversario'), ('1', 'Remanejamento de Função'), ('146', 'Trabalho Remoto (COVID-19)')], max_length=50, unique=True, verbose_name='Tipo de afastamento'),
        ),
    ]
