# Generated by Django 3.1.7 on 2021-03-31 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namp', '0009_auto_20210331_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afastamento',
            old_name='tipificacao',
            new_name='nome',
        ),
    ]
